# Generated by Django 3.0.7 on 2020-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tripadvisor',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
