# Generated by Django 3.0.7 on 2020-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('German', 'German'), ('Vietnamese', 'Vietnamese'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Mexican', 'Mexican'), ('Italien', 'Italien'), ('French', 'French'), ('Hawaiien', 'Hawaiien')], default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisineTopTier',
            field=models.CharField(choices=[('European', 'European'), ('Asian', 'Asian'), ('South-American', 'South-American'), ('North-American', 'North-American'), ('African', 'African'), ('Oceania', 'Oceania')], default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(choices=[('Charlottenburg', 'Charlottenburg'), ('Friedrichshain', 'Friedrichshain'), ('Hellersdorf', 'Hellersdorf'), ('Hohenschoenhausen', 'Hohenschoenhausen'), ('Kreuzberg', 'Kreuzberg'), ('Koepenick', 'Koepenick'), ('Lichtenberg', 'Lichtenberg'), ('Marzahn', 'Marzahn'), ('Mitte', 'Mitte'), ('Moabit', 'Moabit'), ('Neukoelln', 'Neukoelln'), ('Pankow', 'Pankow'), ('Prenzlauer Berg', 'Prenzlauer Berg'), ('Reinickendorf', 'Reinickendorf'), ('Schoeneberg', 'Schoeneberg'), ('Spandau', 'Spandau'), ('Steglitz', 'Steglitz'), ('Tempelhof', 'Tempelhof'), ('Tiergarten', 'Tiergarten'), ('Treptow', 'Treptow'), ('Wedding', 'Wedding'), ('Weißensee', 'Weißensee'), ('Wilmersdorf', 'Wilmersdorf'), ('Zehlendorf', 'Zehlendorf')], default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mealTime1',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Coffee', 'Coffee'), ('Dinner', 'Dinner'), ('Bar', 'Bar')], default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mealTime2',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Coffee', 'Coffee'), ('Dinner', 'Dinner'), ('Bar', 'Bar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mealTime3',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Coffee', 'Coffee'), ('Dinner', 'Dinner'), ('Bar', 'Bar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mealTime4',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Coffee', 'Coffee'), ('Dinner', 'Dinner'), ('Bar', 'Bar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mealTime5',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Coffee', 'Coffee'), ('Dinner', 'Dinner'), ('Bar', 'Bar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mealTime6',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Coffee', 'Coffee'), ('Dinner', 'Dinner'), ('Bar', 'Bar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mealTime7',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Coffee', 'Coffee'), ('Dinner', 'Dinner'), ('Bar', 'Bar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='special1',
            field=models.CharField(blank=True, choices=[('Outdoor Seating', 'Outdoor Seating'), ('Vegetarian Options', 'Vegetarian Options'), ('Vegan Options', 'Vegan Options')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='special2',
            field=models.CharField(blank=True, choices=[('Outdoor Seating', 'Outdoor Seating'), ('Vegetarian Options', 'Vegetarian Options'), ('Vegan Options', 'Vegan Options')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='special3',
            field=models.CharField(blank=True, choices=[('Outdoor Seating', 'Outdoor Seating'), ('Vegetarian Options', 'Vegetarian Options'), ('Vegan Options', 'Vegan Options')], default='', max_length=60),
        ),
    ]
