# Generated by Django 3.0.7 on 2020-06-26 21:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200626_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
            preserve_default=False,
        ),
    ]
