# Generated by Django 3.0.7 on 2020-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200726_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='facebook',
            new_name='facebookLink',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='tripadvisor',
            new_name='instagramLink',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tripadvisorLink',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
