# Generated by Django 3.0.7 on 2020-06-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20200630_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='googleMapsLink',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
