# Generated by Django 3.0.7 on 2020-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_restaurant_googlemapslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('German', 'German'), ('Vietnamese', 'Vietnamese'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Mexican', 'Mexican'), ('Italien', 'Italien'), ('French', 'French'), ('Hawaiien', 'Hawaiien'), ('Russian', 'Russian'), ('Polish', 'Polish'), ('Greek', 'Greek'), ('French', 'French'), ('Spanish', 'Spanish'), ('Taiwanese', 'Taiwanese'), ('Chilenian', 'Chilenian'), ('Columbian', 'Columbian'), ('American', 'American'), ('Turkish', 'Turkish'), ('Syrian', 'Syrian'), ('Austrian', 'Austrian'), ('Japanese', 'Japanese')], max_length=60),
        ),
    ]
