# Generated by Django 3.0.7 on 2020-07-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20200630_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
