# Generated by Django 3.0.7 on 2020-07-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_restaurant_kiez'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('Fusion', 'Fusion'), ('German', 'German'), ('Vietnamese', 'Vietnamese'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Mexican', 'Mexican'), ('Italien', 'Italien'), ('French', 'French'), ('Hawaiien', 'Hawaiien'), ('Russian', 'Russian'), ('Polish', 'Polish'), ('Greek', 'Greek'), ('French', 'French'), ('Spanish', 'Spanish'), ('Taiwanese', 'Taiwanese'), ('Chilenian', 'Chilenian'), ('Columbian', 'Columbian'), ('American', 'American'), ('Turkish', 'Turkish'), ('Syrian', 'Syrian'), ('Austrian', 'Austrian'), ('Japanese', 'Japanese')], max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='kiez',
            field=models.CharField(blank=True, choices=[('Nollendorfkiez', 'Nollendorfkiez'), ('Reuterkiez', 'Reuterkiez'), ('Kungerkiez', 'Kungerkiez'), ('Wrangelkiez', 'Wrangelkiez')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='special1',
            field=models.CharField(blank=True, choices=[('Amazing Outdoor Seating', 'Amazing Outdoor Seating'), ('Extraordinary Flair', 'Extraordinary Flair'), ('Happy Vegans', 'Happy Vegans'), ('Fine Dining', 'Fine Dining')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='special2',
            field=models.CharField(blank=True, choices=[('Amazing Outdoor Seating', 'Amazing Outdoor Seating'), ('Extraordinary Flair', 'Extraordinary Flair'), ('Happy Vegans', 'Happy Vegans'), ('Fine Dining', 'Fine Dining')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='special3',
            field=models.CharField(blank=True, choices=[('Amazing Outdoor Seating', 'Amazing Outdoor Seating'), ('Extraordinary Flair', 'Extraordinary Flair'), ('Happy Vegans', 'Happy Vegans'), ('Fine Dining', 'Fine Dining')], default='', max_length=60),
        ),
    ]
