# Generated by Django 3.0.7 on 2020-07-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20200723_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(choices=[('Charlottenburg', 'Charlottenburg'), ('Friedrichshain', 'Friedrichshain'), ('Hellersdorf', 'Hellersdorf'), ('Hohenschoenhausen', 'Hohenschoenhausen'), ('Kreuzberg', 'Kreuzberg'), ('Koepenick', 'Koepenick'), ('Lichtenberg', 'Lichtenberg'), ('Marzahn', 'Marzahn'), ('Mitte', 'Mitte'), ('Moabit', 'Moabit'), ('Neukoelln', 'Neukoelln'), ('Pankow', 'Pankow'), ('Prenzlauer Berg', 'Prenzlauer Berg'), ('Reinickendorf', 'Reinickendorf'), ('Schoeneberg', 'Schoeneberg'), ('Spandau', 'Spandau'), ('Steglitz', 'Steglitz'), ('Tempelhof', 'Tempelhof'), ('Tiergarten', 'Tiergarten'), ('Treptow', 'Treptow'), ('Wedding', 'Wedding'), ('Weißensee', 'Weißensee'), ('Wilmersdorf', 'Wilmersdorf'), ('Zehlendorf', 'Zehlendorf')], max_length=60),
        ),
    ]
