# Generated by Django 3.0.7 on 2020-07-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20200723_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.District'),
        ),
    ]
